apiVersion: apps/v1
kind: Deployment
metadata:
  name: zai-test-client
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - { key: "app", operator: In, values: [ 'NAME' ] }
              topologyKey: "kubernetes.io/hostname"
