apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

namespace: default
images:
- name: ZAI_TEST_CLIENT
  newName: ${imageRepository}
  newTag: '${projectVersion}'

patches:
- path: patches/ingress-host.yaml
  target:
    kind: Ingress
    name: zai-test-client

patchesStrategicMerge:
  - patches/pod-affinity.yaml

replacements:
- source:
    kind: Deployment
    name: zai-test-client
    fieldPath: metadata.labels.app
  targets:
  - select:
      name: zai-test-client
      kind: Deployment
    fieldPaths:
    - spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution.0.labelSelector.matchExpressions.[key=app].values.0
